name: Android E2E
on:
  pull_request:
    branches:
      - main

jobs:
  android:
    name: Android
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt-openj9'
          java-version: '8'
      - run: yarn
